version: '3'

tasks:
  build:
    cmds:
      - go build -o ./build/app ./cmd/app/app.go
      - go run ./cmd/install/install.go
      - cd && source .bashrc

  source:
    dir: /home/dev
    cmds:
      - source .bashrc
